### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create html page with a suitable background

- [x] create car element and ensure that it shows on the page
- [x] Fix all bugs and errors.
- [x] Delete all commented out code.
- [x] Delete CSS that isn't actually doing anything.
