### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] add css rulesets that rotate the car in each direction of N, S, E, W.
- [x] add javascript event listeners for controlling the direction of the car by using arrow keys
- [x] Create a simple data model that includes which way the car is facing, (north, south, east, or west).
- [x] ensure there's a smooth animation when rotating the car.
- [x] Fix all bugs and errors.
- [x] Delete all console.log()s.
- [x] Delete all commented out code.
- [x] Delete CSS that isn't actually doing anything.
