### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a function to stop the car's movement made possible by the interval ID.
- [x] Add a boolean to your data model to indicate whether or not the car is started.
- [x] Fix all bugs and errors.
- [x] Delete all console.log()s.
- [x] Delete all commented out code.
- [x] Delete CSS that isn't actually doing anything.
