### ISSUE TITLE
User can steer their car.

### ISSUE THREAD

**Issue by kennydpark** [kennydpark/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Ensure that the car's location is being updated on data.location
- [x] Change the car's location depending on which direction it is facing.
- [x] Fix all bugs and errors.
- [x] Delete all console.log()s.
- [x] Delete all commented out code.
- [x] Delete CSS that isn't actually doing anything.
